### Tipos numéricos e aritimética básica

In [1]:
2 + 2

4

In [2]:
2.0 + 2

4.0

In [3]:
# Para números imaginmários, a constante imaginária é im
# note que não é necessário escrever 2.0 -7*im
2.0 - 7im +2

4.0 - 7.0im

In [4]:
# // indica número racional. Nesse caso as operações preservam o tipo
# ou seja, // é diferente de divisão
1//2 + 2//3

7//6

In [5]:
typeof(7//6)

Rational{Int64}

In [6]:
# Racionais e complexos são tipos compostos
typeof(1+im)

Complex{Int64}

In [7]:
# e podemos compor o tipo composto no tipo composto
typeof(1//2+im)

Complex{Rational{Int64}}

In [8]:
# / uma barra só é a boa e velha divisão decimal. Sempre converte pra float
15/5

3.0

In [9]:
# a÷b é o mesmo que div(a,b) e produz o quociente da divisão inteira
# ÷ pode ser escrito como \div[TAB], ou seja, escrevendo \div e apertando TAB.
15÷5

3

In [10]:
12÷5

2

In [11]:
#= funções são definidas pela keyword function
 e finalizadas pela keyword end =#
# Laços (for e while) também são finalizados com end

#= Condicionais (if, else) também terminam em end e seguem a estrutura:
if condição1
    comando
elseif condição2
    comando
else
    comando
end
=#
function divisãointeira(n, p)
    q = n÷p
    r = n%p
    println(n," = $(p)*$(q) + ",r)
end
divisãointeira(131,11)

131 = 11*11 + 10


In [12]:
# * é utilizado para multiplicação, ^ para exponenciação e == para comparação
131 == 11^2 + 10

true

### Strings e Chars

In [13]:
# Strings sempre cercadas por " "
typeof("Olá, pessoal!")

String

In [14]:
# caracteres sempre cercados por ' '
typeof('x')

Char

In [15]:
# λ == \lambda[TAB] é um caracter válido.
# Pode ser usado para definir variáveis e funções
typeof('λ')

Char

In [16]:
typeof('\t')

Char

In [17]:
# Até emojis como o 🐨 == \:koala:[TAB] são caracteres váçidos para esses propósitos
typeof('🐨')

Char

In [18]:
# Strings realmente precisam ser definidas com " "
typeof('Olá, pessoal!')

LoadError: syntax: invalid character literal

### Vetores e Matrizes

    Vetores em Julia são tratados como vetor-coluna.

In [19]:
# ;(a,b) realiza a concatenação vertical de a,b e é o mesmo que vcat(a,b)
vetorcoluna = [1; 2; 3; 4; 5; 6]

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [20]:
# O espaço faz o mesmo que o ; porém realizando a concatenação horizontal.
# 'espaço'(a,b) == hcat(a,b)
vetorlinha = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

Observe que, em ambos os casos, a assinatura de tipo mostra `Array` ao invés de `Vector` e `Matrix`.

Na verdade essas estruturas são subcasos de um typo paramétrico mais abrangente: `Array{T,N}` onde T é o tipo da variável a ser contida no Array de N dimensões.

Por conveniência são definidos os _alias_: `Vector{T} = Array{T,1}` e `Matrix{T} = Array{T,2}`

In [21]:
matriz = [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [22]:
# em Julia a indexação de vetores começa em 1
vetorcoluna[1]

1

In [23]:
# e termina em end
vetorcoluna[end]

6

In [24]:
# end pode ser usado para percorrer o vetor de trás pra frente
vetorcoluna[end-1]

5

In [25]:
# qualquer valor de índice fora do intervalo [1:end] produz erro
vetorcoluna[0]

BoundsError: BoundsError: attempt to access 6-element Array{Int64,1} at index [0]

In [26]:
# ranges são definidos como começo:passo:fim e podem ser usados para
# determinas subvetores ou submatrizes
subvetor = vetorcoluna[3:5]

3-element Array{Int64,1}:
 3
 4
 5

Ao criarmos subvetor copiamos os  dados a uma nova variável.

In [27]:
println(subvetor[2])
subvetor[2] = 131
println(subvetor)
println(vetorcoluna)

4
[3, 131, 5]
[1, 2, 3, 4, 5, 6]


In [28]:
# Note que : requisita todas as colunas
matriz[2:end,:]

2×3 Array{Int64,2}:
 4  5  6
 7  8  9

In [29]:
#= Note também que matrizes possuem indexação de um único índice.
Pode ser útil se for necessário realizar uma operação em todos os
elementos de uma matriz onde a ordem de operação não importa =#
matriz[2:end]

8-element Array{Int64,1}:
 4
 7
 2
 5
 8
 3
 6
 9

Observe que a indexação é feita coluna por coluna

In [30]:
# Por conta dessa indexação, é mais fácil ainda usar vetores linha como vetores
println(vetorlinha)
vetorlinha[2]

[1 2 3]


2

In [31]:
matriz'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  4  7
 2  5  8
 3  6  9

Ao transpor uma matriz o tipo da variável muda por motivo d eeficiência. Em condições normais isso não causa problemas, mas se causar é só converter:

In [32]:
convert(Array, matriz')

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

Pra convencer que raramente será necessário converter:

In [33]:
v = vetorcoluna[1:3]
M = matriz
(v'*M*v)/(v'*v)

16.285714285714285

In [34]:
# Se a e b são matrizes a*b realiza produto matricial.
M'*M

3×3 Array{Int64,2}:
 66   78   90
 78   93  108
 90  108  126

In [35]:
# se desejar realizar produto elemento a elemento, utilize .*
M'.*M

3×3 Array{Int64,2}:
  1   8  21
  8  25  48
 21  48  81

In [36]:
# É possível alterar o valor de elementos das matrizes
M[1,2] = 99.0

99.0

In [37]:
# mas o tipo de elemento não pode ser alterado
M

3×3 Array{Int64,2}:
 1  99  3
 4   5  6
 7   8  9

Note que o Float64 99.0 foi convertido para Int64. O que aconteceria se tivéssemos realizado a atribuição M[1,2] = 131.9 ?

a) Conversão para 131

b) Conversão para 132

Vamos testar!!

In [38]:
M[1,2] = 131.9

InexactError: InexactError: Int64(Int64, 131.9)

O Julia não decide por você o que é melhor fazer nesse caso. Alguma das seguintes funções deve ser utilizada: `round`, `floor` ou `ceil`

In [39]:
[i*i for i in 1:5]

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [40]:
[i*j for i in 1:5,j in 1:4]

5×4 Array{Int64,2}:
 1   2   3   4
 2   4   6   8
 3   6   9  12
 4   8  12  16
 5  10  15  20

### Tipo Missing

Inpirado no "Not Available" do R, `NA`, o Julia oferece o `missing`

In [41]:
?Missing

search: Missing missing MissingException ismissing skipmissing



```
Missing
```

A type with no fields whose singleton instance [`missing`](@ref) is used to represent missing values.


In [42]:
# missing estraga toda e qualquer conta ou operação
missing + 2

missing

In [43]:
# missing também estraga o tipo do vetor
x = [1; 2; missing; 4]

4-element Array{Union{Missing, Int64},1}:
 1       
 2       
  missing
 4       

In [44]:
# O mesmo que 2 in x
# Pode ser escrito como 2 \in[TAB] x
2 ∈ x

true

In [45]:
missing in x

missing

In [46]:
# existem algumas funções para lidar com os missings
# mas é importante ver com cuidado como elas funcionam
# x contém missings mas x não é missing
ismissing(x)

false

In [47]:
any(ismissing,x)

true

In [48]:
y = collect(skipmissing(x))

3-element Array{Int64,1}:
 1
 2
 4

In [49]:
# ∘ == \circ[TAB] é um operador de composição de funções
filtmiss = collect∘skipmissing
filtmiss(x)

3-element Array{Int64,1}:
 1
 2
 4

### Modos do REPL no IJulia

In [50]:
# Modo shell. Funciona bem em sistemas Unix, ou seja, não funciona bem em Windows
;git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Preliminares.ipynb
	modified:   componentesprincipais.ipynb
	modified:   fileIO.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [51]:
# Modo ajuda
?cumsum

search: cumsum cumsum!



```
cumsum(A; dims::Integer)
```

Cumulative sum along the dimension `dims`. See also [`cumsum!`](@ref) to use a preallocated output array, both for performance and to control the precision of the output (e.g. to avoid overflow).

# Examples

```jldoctest
julia> a = [1 2 3; 4 5 6]
2×3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> cumsum(a, dims=1)
2×3 Array{Int64,2}:
 1  2  3
 5  7  9

julia> cumsum(a, dims=2)
2×3 Array{Int64,2}:
 1  3   6
 4  9  15
```

---

```
cumsum(x::AbstractVector)
```

Cumulative sum a vector. See also [`cumsum!`](@ref) to use a preallocated output array, both for performance and to control the precision of the output (e.g. to avoid overflow).

# Examples

```jldoctest
julia> cumsum([1, 1, 1])
3-element Array{Int64,1}:
 1
 2
 3

julia> cumsum([fill(1, 2) for i in 1:3])
3-element Array{Array{Int64,1},1}:
 [1, 1]
 [2, 2]
 [3, 3]
```


In [52]:
# Modo Package Manager
]status

    Status `~/.julia/environments/v1.0/Project.toml`
  [c52e3926] Atom v0.7.6
  [a93c6f00] DataFrames v0.13.1
  [31c24e10] Distributions v0.16.4
  [28b8d3ca] GR v0.34.1
  [7073ff75] IJulia v1.11.1
  [d0351b0e] InspectDR v0.3.2
  [e5e0dc1b] Juno v0.5.3
  [6f286f6a] MultivariateStats v0.6.0
  [ccf2f8ad] PlotThemes v0.3.0
  [58dd65bb] Plotly v0.2.0
  [f0f68f2c] PlotlyJS v0.11.1
  [91a5bcdd] Plots v0.20.2
  [438e738f] PyCall v1.18.4
  [d330b81b] PyPlot v2.6.3
  [60ddc479] StatPlots v0.8.1
  [b8865327] UnicodePlots v0.3.1
