### Tipos numéricos e aritimética básica

In [1]:
2 + 2

4

In [2]:
2.0 + 2

4.0

In [3]:
2.0 - 7im +2

4.0 - 7.0im

In [4]:
1//2 + 2//3

7//6

In [5]:
typeof(7//6)

Rational{Int64}

In [30]:
typeof(1+im)

Complex{Int64}

In [31]:
typeof(1//2+im)

Complex{Rational{Int64}}

In [11]:
15/5

3.0

In [12]:
15÷5

3

In [13]:
12÷5

2

In [24]:
function euclides(n, p)
    q = n÷p
    r = n%p
    println(n," = $(p)⋅$(q) + ",r)
end
euclides(131,11)

131 = 11⋅11 + 10


In [23]:
131 == 11^2 + 10

true

### Strings e Chars

In [28]:
typeof("Olá, pessoal!")

String

In [26]:
typeof('\t')

Char

In [29]:
typeof('Olá, pessoal!')

LoadError: syntax: invalid character literal

### Vetores e Matrizes

    Vetores em Julia são tratados como vetor-coluna.

In [45]:
vetorcoluna = [1; 2; 3; 4; 5; 6]

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [33]:
vetorlinha = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

Observe que, em ambos os casos, a assinatura de tipo mostra `Array` ao invés de `Vector` e `Matrix`.

Na verdade essas estruturas são subcasos de um typo paramétrico mais abrangente: `Array{T,N}` onde T é o tipo da variável a ser contida no Array de N dimensões.

Por conveniência são definidos os _alias_: `Vector{T} = Array{T,1}` e `Matrix{T} = Array{T,2}`

In [56]:
matriz = [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [46]:
vetorcoluna[1]

1

In [47]:
vetorcoluna[end]

6

In [55]:
vetorcoluna[end-1]

5

In [44]:
vetorcoluna[-1]

BoundsError: BoundsError: attempt to access 3-element Array{Int64,1} at index [-1]

In [48]:
vetorcoluna[3:5]

3-element Array{Int64,1}:
 3
 4
 5

In [51]:
matriz[2:end,:]

2×3 Array{Int64,2}:
 4  5  6
 7  8  9

In [52]:
matriz[2:end]

8-element Array{Int64,1}:
 4
 7
 2
 5
 8
 3
 6
 9

Observe que a indexação é feita coluna por coluna

In [57]:
matriz'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  4  7
 2  5  8
 3  6  9

Se a troca de tipo der problema, é só converter:

In [59]:
convert(Array, matriz')

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

Mas é raro que seja necessário

In [60]:
v = vetorcoluna[1:3]
m = matriz
(v'*m*v)/(v'*v)

16.285714285714285

In [65]:
m'*m

3×3 Array{Int64,2}:
 66   78   90
 78   93  108
 90  108  126

In [66]:
m'.*m

3×3 Array{Int64,2}:
  1   8  21
  8  25  48
 21  48  81

In [76]:
m[1,2] = 99.0

99.0

In [91]:
m

3×3 Array{Int64,2}:
 1  99  3
 4   5  6
 7   8  9

In [86]:
[i*i for i in 1:5]

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [87]:
[i*j for i in 1:5,j in 1:4]

5×4 Array{Int64,2}:
 1   2   3   4
 2   4   6   8
 3   6   9  12
 4   8  12  16
 5  10  15  20

### Modos do REPL no IJulia

In [35]:
;git status

On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.ipynb_checkpoints/
	Preliminares.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [37]:
?cumsum

search: cumsum cumsum!



```
cumsum(A; dims::Integer)
```

Cumulative sum along the dimension `dims`. See also [`cumsum!`](@ref) to use a preallocated output array, both for performance and to control the precision of the output (e.g. to avoid overflow).

# Examples

```jldoctest
julia> a = [1 2 3; 4 5 6]
2×3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> cumsum(a, dims=1)
2×3 Array{Int64,2}:
 1  2  3
 5  7  9

julia> cumsum(a, dims=2)
2×3 Array{Int64,2}:
 1  3   6
 4  9  15
```

---

```
cumsum(x::AbstractVector)
```

Cumulative sum a vector. See also [`cumsum!`](@ref) to use a preallocated output array, both for performance and to control the precision of the output (e.g. to avoid overflow).

# Examples

```jldoctest
julia> cumsum([1, 1, 1])
3-element Array{Int64,1}:
 1
 2
 3

julia> cumsum([fill(1, 2) for i in 1:3])
3-element Array{Array{Int64,1},1}:
 [1, 1]
 [2, 2]
 [3, 3]
```


In [38]:
]status

    Status `~/.julia/environments/v1.0/Project.toml`
  [c52e3926] Atom v0.7.6
  [a93c6f00] DataFrames v0.13.1
  [31c24e10] Distributions v0.16.4
  [28b8d3ca] GR v0.34.1
  [7073ff75] IJulia v1.11.1
  [e5e0dc1b] Juno v0.5.3
  [6f286f6a] MultivariateStats v0.6.0
  [ccf2f8ad] PlotThemes v0.3.0
  [91a5bcdd] Plots v0.20.2
  [d330b81b] PyPlot v2.6.3
  [60ddc479] StatPlots v0.8.1
  [b8865327] UnicodePlots v0.3.1
